name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: "5.5"
    - name: Build
      run: swift build -v

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
